swiftmailer:
    transport: smtp
    auth_mode: login
    port: 587
    encryption: ssl
    host: mail.infomaniak.com
    username: contact@isis-cp.fr
    password: Pabloneruda973
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    stream_options: 
      ssl:
        allow_self_signed: true
        verify_peer: false
        verify_peer_name: false
        
# swiftmailer:
#     transport: smtp
#     auth_mode: login
#     port: 587
#     encryption: ssl
#     host: smtp.office365.com
#     username: kwach@hotmail.fr
#     password: Ytrezaytreza
#     url: '%env(MAILER_URL)%'
#     spool: { type: 'memory' }
#     stream_options: 
#       ssl:
#         allow_self_signed: true
#         verify_peer: false
#         verify_peer_name: false
